### ISSUE TITLE
[STORY] Implement standard Freesurfer preprocessing in an Arcana analysis class

### ISSUE THREAD

**Issue by Mahdieh-dst** [Australian-Imaging-Service/pipelines#97] opened 2022-06-27 06:01 UTC
### Description
As a researcher, I want to implement standard Freesurfer preprocessing on T1/T2 images in an Arcana analysis class so that I can do brain extraction and segmentation, surface-based brain parcellation/reconstruction and get access to full output folder of recon-all.

### Acceptance Criteria
- [ ] 1.  A Freesurfer recon-all column is added to an analysis class in Arcana
- [ ] 2. A pipeline method is implemented to derive that column 
- [ ] 3. The pipeline is successfully tested on suitable test data

**Comment by tclose** [comment] 2022-10-01 11:01
duplicate of #143

**Closed by tclose** 2022-10-01 11:01 UTC
Labels: pipelines, story, analysis-design, mid-level
