### ISSUE TITLE
[STORY] Compare generated connection graphs between ported pydra and original nipype workflows

### ISSUE THREAD

**Issue by Mahdieh-dst** [Australian-Imaging-Service/pipelines#219] opened 2022-10-26 00:52 UTC
### Metadata

Epic:
Feature: #217 
Feature Release: 1
Required knowledge: mid-level

### Description
Compare the connection graphs generated from the original nipype workflow with the converted pydra workflow. Both Nipype and Pydra workflows can generate "DOT" files containing the connections between their nodes. Would be good to create a test function that can be run after the conversion to check that the connection graphs are equivalent.

### Acceptance Criteria

- [ ] 1. The test function is able to verify the connection graph matches between equivalent Nipype and Pydra workflows

**Comment by tclose** [comment] 2022-11-15 00:19
duplicate of #220

**Closed by tclose** 2022-11-15 00:19 UTC
Labels: pipelines, story, mid-level
